<script setup lang="ts">
import{X,Star,Download,ImageOff,MapPin}from'lucide-vue-next';
import{apiAssetUrl}from '@/services/api';
import type{DesenhoDetalhe}from '@/types/api';
defineProps<{design:DesenhoDetalhe}>();
defineEmits<{close:[];favorite:[design:DesenhoDetalhe]}>();
const number=new Intl.NumberFormat('pt-BR');
</script>
<template><div class="fixed inset-0 z-[60] flex items-center justify-center bg-ink/60 p-4" role="dialog" aria-modal="true" @click.self="$emit('close')"><div class="grid max-h-[92vh] w-full max-w-[900px] overflow-y-auto rounded-3xl bg-white shadow-2xl md:grid-cols-2"><div class="flex min-h-80 items-center justify-center bg-cream p-8"><img v-if="design.preview_url" :src="apiAssetUrl(design.preview_url)!" :alt="`Preview de ${design.nome}`" class="max-h-[520px] w-full object-contain"/><ImageOff v-else :size="48" class="text-muted"/></div><div class="relative p-6 md:p-8"><button class="absolute right-5 top-5 rounded-full border border-line p-2" aria-label="Fechar" @click="$emit('close')"><X/></button><div class="pr-14"><h2 class="font-serif text-3xl text-purple">{{design.nome}}</h2><button class="mt-3 rounded-full border border-line p-2" @click="$emit('favorite',design)"><Star :class="design.favorito?'fill-gold text-gold':'text-muted'"/></button></div><span v-if="design.categoria" class="mt-5 inline-block rounded-full bg-[#EDF3ED] px-3 py-1 text-sm text-sage">{{design.categoria.nome}}</span><p v-if="design.descricao" class="mt-5 text-sm leading-6 text-muted">{{design.descricao}}</p><h3 class="mb-3 mt-7 font-semibold text-purple">Variações disponíveis</h3><div class="space-y-3"><div v-for="item in design.matrizes" :key="item.id" class="rounded-2xl border border-line p-4"><div class="flex items-start justify-between gap-3"><div><p class="font-semibold">{{item.rotulo_tamanho||item.formato.toUpperCase()}}</p><p class="mt-1 text-xs text-muted">{{item.largura_mm}} × {{item.altura_mm}} mm · {{item.quantidade_cores}} cores · {{number.format(item.quantidade_pontos)}} pontos</p></div><a :href="apiAssetUrl(item.download_url)!" class="primary-button shrink-0 !px-3 !py-2 text-sm"><Download :size="17"/><span class="hidden sm:inline">Baixar .PES</span></a></div><div v-if="item.origem_identificacao||item.caminho_relativo_origem" class="mt-3 flex gap-2 rounded-xl bg-cream p-3 text-xs text-muted"><MapPin :size="16" class="shrink-0"/><span><strong>Origem do arquivo</strong><br/>{{[item.origem_identificacao,item.caminho_relativo_origem].filter(Boolean).join(' · ')}}</span></div></div><p v-if="!design.matrizes.length" class="text-sm text-muted">Nenhuma variação disponível.</p></div></div></div></div></template>
